name: Check Basekit
on: 
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

env:
  BASEKIT_VERSION_URL: https://www.intel.com/content/www/us/en/developer/tools/oneapi/oneapi-toolkit-download.html
  OPENCL_VERSION_URL: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  check-basekit-download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
      - name: Collect .exe URLs
        run: |
            echo "basekit=$(grep -oP -m 1 '(?<=WINDOWS_BASEKIT_URL: )\S+' .ci/pipeline/ci.yml)" >> $GITHUB_ENV
            echo "opencl=$(grep -oP -m 1  'https?://[^ ]+\.exe' .ci/scripts/collect_opencl_rt.ps1)" >> $GITHUB_ENV
      - name: Prepare playwright
        run: |
          pip install playwright
      - name: Query basekit
        run: python .ci/scripts/check_basekit.py $basekit $BASEKIT_VERSION_URL
      - name: Query opencl
        run: python .ci/scripts/check_basekit.py $opencl $OPENCL_VERSION_URL
      - name: Attempt PR
        run: |
          date > probe.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b test-permission-branch
          git add .
          git commit -m "Permission probe"
          git push origin test-permission-branch
          gh pr create --title "Test PR" --body "Checking if Actions can make PRs"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
