name: Check Basekit
on: 
  schedule:
    - cron: "0 0 * * 6"
  workflow_dispatch:

env:
  BASEKIT_VERSION_URL: https://www.intel.com/content/www/us/en/developer/tools/oneapi/oneapi-toolkit-download.html
  OPENCL_VERSION_URL: https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref_name }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  contents: write

jobs:
  check-basekit-download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Collect main URLs
        run: |
          echo "main_basekit=$(grep -oP -m 1 "(?<=WINDOWS_BASEKIT_URL: )[^\\s']+" .ci/pipeline/ci.yml)" >> $GITHUB_ENV
          echo "main_opencl=$(grep -oP -m 1  'https?://[^ ]+\.exe' .ci/scripts/collect_opencl_rt.ps1)" >> $GITHUB_ENV
      - name: Query basekit URL
        run: |
          curl -L --retry 3 -o basekit.html $BASEKIT_VERSION_URL
          QUERY_BASEKIT=$(grep -oP 'https?://[^ "]+\.exe' basekit.html | head -1)
          QUERY_VERSION=$(echo "$QUERY_BASEKIT" | grep -oP '[\d.]+(?=_offline)')
          echo "query_basekit=$QUERY_BASEKIT" >> $GITHUB_ENV
          echo "query_basename=$QUERY_VERSION" >> $GITHUB_ENV
      - name: Query opencl URL
        run: |
          curl -L --retry 3 -o opencl.html $OPENCL_VERSION_URL
          grep -oP 'https?://[^ "]+\.exe' opencl.html | head -1
          QUERY_OPENCL=$(grep -oP 'https?://[^ "]+\.exe' opencl.html | head -1)
          QUERY_VERSION=$(echo "$QUERY_OPENCL" | grep -oP '[\d.]+(?=exe)')
          echo "query_opencl=$QUERY_OPENCL" >> $GITHUB_ENV
          echo "query_openclname=$QUERY_VERSION" >> $GITHUB_ENV
      - name: Create Basekit Update PR
        if: ${{ env.main_basekit != env.query_basekit }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b basekit/${{ env.query_basename }}
          sed -i 's|${{ env.main_basekit }}|${{ env.query_basekit }}|g' .ci/pipeline/ci.yml
          git commit -m "Update Windows Basekit to ${{ env.query_basename }}"
          git push origin basekit/${{ env.query_basename }}
          gh pr create --title "Update Windows Basekit to ${{ env.query_basename }}" --body "autogenerated"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create OpenCL Update PR
        if: ${{ env.main_opencl != env.query_opencl }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b test-permission-branch
          git add .
          git commit -m "Permission probe"
          git push origin test-permission-branch
          gh pr create --title "Update OpenCL Windows CPU runtime to " --body "autogenerated"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
