name: Enforce Labels
on:
  pull_request:
    branches: [ "main" ]

env:
  LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}

jobs:
  label_checker:
    name: Please include labels on your pull request
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: test
        run: if [[ "${{ env.LABELS }}" == "[]" ]]; then exit 1; fi
